version: '3'
services:
  mysql:
    container_name: db
    restart: unless-stopped
    image: mysql:5.7.34
    environment:
      MYSQL_DATABASE: webchat_project
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./database/dbdata:/var/lib/mysql
    ports:
    - 33866:3386
    - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci